#!/bin/sh

# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask snips-dialogue.service > /dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled snips-dialogue.service
then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable dns-update.service > /dev/null || true
	deb-systemd-invoke start dns-update
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state dns-update.service > /dev/null || true
fi